apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-daemonset-waiter
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-daemonset-waiter
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidia-daemonset-waiter
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-daemonset-waiter
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-daemonset-waiter
subjects:
- kind: ServiceAccount
  name: nvidia-daemonset-waiter
  namespace: nvidia-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-daemonset-waiter
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvidia-daemonset-waiter
subjects:
- kind: ServiceAccount
  name: nvidia-daemonset-waiter
  namespace: nvidia-gpu-operator
