apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-serving
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kanekoh/mta-workshop-env.git
    targetRevision: main
    path: gitops/environments/ai-serving/resources/model-serving
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: model-serving
  ignoreDifferences:
    - group: serving.kserve.io
      kind: InferenceService
      jsonPointers:
        - /metadata/annotations
        - /spec/predictor/model/runtime
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /metadata/annotations
        - /spec/listeners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
