apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-post
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kanekoh/mta-workshop-env.git
    targetRevision: main
    path: gitops/environments/ai-serving/resources/openshift-ai-post
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 30
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 10m
