apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: "stable-v26"
  installPlanApproval: Automatic
  name: keycloak-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

