apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloud-native-postgresql
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: "stable-v1"
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace

