apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: granite-2b
        litellm_params:
          model: openai/granite-3-3-2b-instruct
          api_base: http://granite-2b-predictor.model-serving.svc.cluster.local/v1
          api_key: "no-key"

    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      database_url: os.environ/DATABASE_URL
