apiVersion: v1
kind: Service
metadata:
  name: litellm-postgresql
  namespace: litellm
  labels:
    app: litellm-postgresql
spec:
  selector:
    app: litellm-postgresql
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
