apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-postgresql
  namespace: litellm
  labels:
    app: litellm-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
