apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litellm
  namespace: litellm
  labels:
    app: litellm
spec:
  to:
    kind: Service
    name: litellm
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
