apiVersion: v1
kind: Service
metadata:
  name: groupsync-mock
  namespace: groupsync-mock
  labels:
    app: groupsync-mock
spec:
  selector:
    app: groupsync-mock
  ports:
    - name: http
      port: 8080
      targetPort: 8080
