apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: hk-bare
  centralEndpoint: "central-rhacs-operator.apps.rosa.hk-bare.x388.p3.openshiftapps.com:443"
  admissionControl:
    listenOnCreates: true
    listenOnUpdates: true
    listenOnEvents: true
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
