apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: nvidia-gpu
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: ''
  displayName: NVIDIA GPU
  enabled: true
  identifier: nvidia.com/gpu
  tolerations: []