# FlowCollector for Network Observability - uses dedicated LokiStack (netobserv in netobserv namespace)
# Must be named "cluster"; only one instance per cluster.
# Requires Loki Operator and LokiStack "netobserv" to be deployed first. Secret loki-s3-credentials in netobserv.
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  agent:
    type: eBPF  # eBPF モードであることを確認
    ebpf:
      # ここが重要です
      features:
        - PacketDrop   # パケットドロップの理由を含めて収集
        - FlowRTT      # TCP の RTT (Handshake latency) を収集
        - DNSTracking  # (任意) DNSの応答時間なども取りたい場合
      privileged: true # PacketDrop を有効にするには特権モードが必要です  namespace: netobserv
  deploymentModel: Direct
  loki:
    mode: LokiStack
    lokiStack:
      name: netobserv
      namespace: netobserv
