apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payload-processing-allow
  namespace: openshift-ingress
spec:
  podSelector:
    matchLabels:
      app: payload-processing
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
