apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-2b
  namespace: model-serving
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: oci://registry.redhat.io/rhai/modelcar-granite-3-3-2b-instruct:3.0
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
