apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: granite-2b
  namespace: model-serving
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    alpha.maas.opendatahub.io/tiers: '[]'
spec:
  baseRefs:
    - name: custom-nvidia-cuda-gpu
  model:
    name: granite-3-3-2b-instruct
    uri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-2b-instruct
  replicas: 1
  router:
    route: {}
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
