apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store
  namespace: llm-serving
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi