apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: openshift-mta
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-v8.0
  installPlanApproval: Automatic
  name: mta-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: ROLEARN
      valueFrom:
        configMapKeyRef:
          name: operator-rolearn
          key: rolearn
