apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://litellm:litellm-demo-password-change-me@litellm-postgresql.litellm.svc.cluster.local:5432/maas?sslmode=disable"
