apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: granite-2b-basic
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  owner:
    groups:
      - name: basic
  modelRefs:
    - name: granite-2b
      namespace: model-serving
      tokenRateLimits:
        - limit: 100000
          window: "1h"
  priority: 5
