apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: oadp-operator
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - openshift-adp
  upgradeStrategy: Default
