apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mta-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kanekoh/mta-workshop-env.git
    targetRevision: main
    path: gitops/operators/mta-operator
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-mta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
